name: Deploy SIPAT Terpadu to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to Server via SSH
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Connect to Tailscale
        uses: tailscale/github-action@v3
        with:
          authkey: ${{ secrets.TAILSCALE_AUTHKEY }}

      - name: Executing remote SSH commands using ssh key
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SERVER_PORT || 22 }}
          script: |
            cd /home/arif/Projek/SIPAT_Terpadu
            chmod +x deploy.sh
            ./deploy.sh
